### ISSUE TITLE
plone.app.standardtiles.portletManager should not be listed into plone toolbar

### ISSUE THREAD

**Issue by simahawk** [plone/plone.app.standardtiles#10]
"Manage portlets" menu into plone toolbar is listing this manager that should be used only for portlets to be inserted via tiles.

**Comment by datakurre** [comment]
Simone Orsi wrote:
> "Manage portlets" menu into plone toolbar is listing this manager that
> should be used only for portlets to be inserted via tiles.

@simahawk Would you be able to check if there's any sensible way to make 
it hidden in Plone 5?
