### ISSUE TITLE
Contentlisting tile should default to list the contents of the current folder

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.standardtiles#11]
But how? How can one form a such query with plone.app.querystring, which only returns on level *contents* of the folder, but not the folder itself?

**Comment by datakurre** [comment]
After https://github.com/plone/plone.app.querystring/pull/36 has been merged, default value adapter also for sort_on can be enabled.

**Comment by thet** [comment]
@datakurre did you think of using plone.app.contentlisting? When this pull request is merged, it works for folders and collections alike: https://github.com/plone/plone.app.contentlisting/pull/6
You just need to call the @@contentlisting view and get all items of the folder or collection.

**Comment by datakurre** [comment]
@thet Not yet, because the original contentslistng stdtile used query. Maybe there should be separate tiles for folderlisting and queries, but not sure.

**Comment by thet** [comment]
Aha, queries created with the querystring widget? That's of course nice. contextual contentlisting also makes sense, IMO

**Comment by datakurre** [comment]
@thet Yes. I like the ideo of having just simple plone.app.contentlisting instead of that querystring widget based tile and "Collection tile" (or some better name), but I guess it's UI wise simpler to just have a one tile for both purposes. Not sure, though.

**Comment by simahawk** [comment]
I think that if the current solution doesn't add overhead when rendering the listing is really ok to stick w/ it, above all because you don't know if you want to list the current context or another one.
It should default to current one, of course.

**Comment by datakurre** [comment]
@simahawk Thanks. Then let's keep the current content listing tile then. And I'll add the getObjPositionInParent configuration into p.a.standardtiles so that we can already have content listing tile with proper defaults.

Proxy / Existing content tile would solve the "related collection" use-case.
