### ISSUE TITLE
tests are broken

### ISSUE THREAD

**Issue by simahawk** [plone/plone.app.standardtiles#14]
a lot of stuff has been changed and tests are not updated...

**Comment by datakurre** [comment]
They were broken already year ago :/

Simone Orsi kirjoitti su toukokuuta 24 13:12:20 2015 GMT+0300:

**Comment by datakurre** [comment]
We should try to fix test before Arnhem sprint, but let's not let this be blocker for alpha release.

**Comment by gforcada** [comment]
Is there a KGS/cfg where we can run tests for the whole suite? This one for example: https://github.com/plone/buildout.coredev/blob/5.0/plips/plip-mosaic.cfg ?

We can create a jenkins job with it so that any fix testing effort can be tracked easily :)

**Comment by gforcada** [comment]
There you go: http://jenkins.plone.org/job/plip-mosaic/

**Comment by datakurre** [comment]
I disabled all but field tiles tests (which I fixed) to get p.a.stdtiles' tests running.

plone/app/standardtiles/configure.zcml

**Comment by datakurre** [comment]
Fixed in https://github.com/plone/plone.app.standardtiles/pull/15
