### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by thet** [plone/plone.app.standardtiles#141]
This fix is needed for anything related to mosaic:
https://github.com/plone/plone.app.standardtiles/pull/140

Because: 
https://graz.social/@thet/110239134884755158

I'd also happy about release rights for "thet".

**Comment by mauritsvanrees** [comment]
I have released `plone.app.standardtiles` 3.0.1.  I will add this to the ecosystem versions in Plone 6.0.4.

@thet You have a PyPI invite now.
Thanks!

**Comment by thet** [comment]
thanks @mauritsvanrees ! 
i also accepted the pypi invitation.
