### ISSUE TITLE
Impossible to add/save existing content tile

### ISSUE THREAD

**Issue by boulch** [plone/plone.app.standardtiles#149]
When I try to add existing content tile, if plone.app.standardtiles.content_views is empty, the field `view_template` (display mode) is never valid because of :

https://github.com/plone/plone.app.standardtiles/blob/4579cb8be5f86068a5ff52af3bc6a7232d2432a8/src/plone/app/standardtiles/existingcontent.py#L272

Field is required but value is always empty.

![Screenshot from 2023-11-14 11-30-18](https://github.com/plone/plone.app.standardtiles/assets/10205875/a241e65a-5a04-4f84-80a5-f341ca66bd52)

In the following code, we check if view_template is empty to get default view (`context.getLayout`) :

https://github.com/plone/plone.app.standardtiles/blob/4579cb8be5f86068a5ff52af3bc6a7232d2432a8/src/plone/app/standardtiles/existingcontent.py#L177

To fix that, IMHO, the field `view_template` must not be required here :

https://github.com/plone/plone.app.standardtiles/blob/4579cb8be5f86068a5ff52af3bc6a7232d2432a8/src/plone/app/standardtiles/existingcontent.py#L125-L129

**Comment by petschki** [comment]
Hi this got fixed with the latest release. See https://github.com/plone/plone.app.standardtiles/pull/159
