### ISSUE TITLE
documentByLine doesn't find displayPublicationDateInByline property in Plone 5

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.standardtiles#19]
site_properties have been emptied

**Comment by agitator** [comment]
i'd update this tile with the moment pattern from mockup, but what about plone4?

what addons do make use of this package, other than mosaic?
do we try to support plone4 and plone5?

**Comment by datakurre** [comment]
@agitator I'd like to keep Plone 4 compatibility as long as it's trivial. There are also other tiles, which use site_properties on Plone 4 and registry on Plone 5. If you'd like to have different template for Plone 5, simply split tile registration into different registration for Plone 4 and Plone 5 using zcml:condition="have plone-5" and "not-have plone-5"

**Comment by jensens** [comment]
FYI: i think we skipped with 2.0 already the plone 4 compat.

**Comment by jensens** [comment]
needs update then https://github.com/plone/plone.app.standardtiles/blob/master/plone/app/standardtiles/common.py#L338

**Comment by datakurre** [comment]
@jensens Yes. 4.x compat can be dropped in master. Yet, it would be nice to see those explicit 4.x removals in separate commits to make it easier to backport compatible fixes into 1.x when required.

My push for 4.x support in 1.x (agains the more general opinion) was to have a manual way to migrate all custom legacy composite content types to Mosaic views to ease 5.x migration.

**Comment by datakurre** [comment]
That said. The requirement of p.a.widgets for Plone 4.x did already put Mosaic in very marginal on Plone 4.x (yet, it should not require plone.app.contenttypes and it's hard-to-guess version pinnings, only p.a.widgets).

**Comment by datakurre** [comment]
@agitator Could you still do this?
