### ISSUE TITLE
Summary view of content listing tile breaks

### ISSUE THREAD

**Issue by danmur** [plone/plone.app.standardtiles#21]
When I create a content listing tile and set it to summary view I get this:
https://bitbucket.org/snippets/danmur/8L7oa

I've fixed it in my project using jbot but I'm not sure if my changes are any good, especially the image one as I'm not sure what it was doing before, but here's my patch in case it's useful:

```
diff --git a/src/plone.app.standardtiles/plone/app/standardtiles/templates/summary_view.pt b/src/hatchd.plone.boxofsand/src/hatchd/plone/boxofsand/browser/overrides/plone.app.standardtiles.templates.summary_view.pt
index 5ee4de4..c839bf8 100644
--- a/src/plone.app.standardtiles/plone/app/standardtiles/templates/summary_view.pt
+++ b/src/hatchd.plone.boxofsand/src/hatchd/plone/boxofsand/browser/overrides/plone.app.standardtiles.templates.summary_view.pt
@@ -14,15 +14,18 @@
                              item_type item/Type;
                              item_creator item/Creator;
                              item_description item/Description;
-                             item_modified item/ModificationDate">
+                             item_modified item/ModificationDate;
+                             original_context nocall:options/original_context|context;
+                             pas_member original_context/@@pas_member;">
         <div class="tileItem visualIEFloatFix"
              tal:define="item_object item/getObject;">
           <a href="#"
-             tal:condition="exists:item_object/image_thumb"
+             tal:condition="item_object/image | nothing"
              tal:attributes="href item_url">
             <img src=""
                  alt=""
-                 tal:replace="structure python: path('nocall:item_object/tag')(scale='thumb', css_class='tileImage')" />
+                 tal:define="scales item_object/@@images"
+                 tal:replace="structure python: scales.tag('image', scale='thumb', css_class='tileImage')" />
           </a>
           <h2 class="tileHeadline"
               metal:define-macro="listitem">
@@ -75,7 +78,7 @@
               </span>
             </tal:event>
             <tal:newsitem condition="python: item_type == 'News Item'">
-              <tal:name tal:condition="item_creator" tal:define="author item_creator">
+              <tal:name tal:condition="item_creator" tal:define="author python:pas_member.info(item_creator)">
                 <a href="#"
                    tal:attributes="href string:author/${author/username}"
                    tal:content="author/username"
```

The author change I stole from one of the other content listing view templates and the image one I wrote to work with my content type, which is a News item with a lead image.

**Comment by datakurre** [comment]
@danmur Thanks. Strange error, because the template was supposed to be checking existence of that attribute. Image fix is probably ok, but why was the author fix required?

**Comment by danmur** [comment]
Yes, there is something a bit weird going on... I was in a bit of a rush when I did this, let me check over it again and clean it up properly and I'll make a pull request for it.

Do you know what kind of image the existing code was handling? That update I made was for the lead image behaviour and it works with that but am wondering now if it will have broken something else.

**Comment by datakurre** [comment]
@danmur That's very old template, which has only been fixed for errors. I'd suspect that it's made originally for Archetypes' News Item, and if it happens to work with Dexterity News Item, it's only because of possible backwards compatibilty in that. I think, supporting Dexterity News Item only is ok.

**Comment by vangheem** [comment]
With latest, this is no longer an issue.
