### ISSUE TITLE
Weak permissions

### ISSUE THREAD

**Issue by thet** [plone/plone.app.standardtiles#23]
Most of the plone.app.standardtiles have very weak add permission configurations. 

For example, in https://github.com/plone/plone.app.standardtiles/blob/master/plone/app/standardtiles/media.zcml#L12 the "embed tile" has the add persmission ``zope.Public``, the "existing content" tile has the permission ``zope.View``.

Besides of beeing way weak, it also looks very wrong. There is a permission called "plone.app.tiles.AddTile", which looks like a better choice. But plone.tiles allows to define a ``edit_permission`` and ``delete_permission`` alongside the ``add_permission``.

I suggest to create ``plone.app.tiles.EditTile`` and ``plone.app.tiles.DeleteTile`` permissions and use those together with ``plone.app.tiles.AddTile`` for all tiles defined in plone.app.standardtiles. Or maybe even defining all those permissions in plone.tiles instead...

**Comment by agitator** [comment]
@datakurre @vangheem  opions?

**Comment by datakurre** [comment]
zope.Public is probably wrong and has history back to some Living statues sprint, where plone.app.standardtiles were first made

Permissions are mess because of the messy history of these packages. I'm ok for fixing those, but I may not have time before spring myself.

**Comment by thet** [comment]
@datakurre no prob, I'm fixing this myself... we're going to use mosaic for a client project but have to disallow normal content editors to change layouts and restrict ui elements to the minimum necessary set. we want to do that with permissions. so, next step would be to fix the mosaic toolbar to show only elements, the user is allowed to interact with.

**Comment by vangheem** [comment]
@thet do you have a PR? I'm inspecting and I'm very surprised to see such weak permissions. Public for add permissions everywhere?

Also, I noticed the lock info showing up for anonymous which I imagine should be handled by using a view permission instead.

**Comment by vangheem** [comment]
Here is a PR: https://github.com/plone/plone.app.standardtiles/pull/24

**Comment by thet** [comment]
@vangheem tnx for the pull! @jensens already merged.
I didn't prepare a pull since I didn't reach the part of the project, where we're going to integrate mosaic.
