### ISSUE TITLE
Deprecate usage IOmittedField

### ISSUE THREAD

**Issue by thet** [plone/plone.app.standardtiles#28]
``plone.app.blocks.interfaces.IOmittedField`` was deprecated in PR https://github.com/plone/plone.app.blocks/pull/33

It's usage should also be deprecated here: https://github.com/plone/plone.app.standardtiles/blob/master/plone/app/standardtiles/utils.py#L105

Right? /cc @jensens

**Comment by jensens** [comment]
yes.
