### ISSUE TITLE
Is there any calendar tile somewhere?

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.standardtiles#31]
I have a requirement for a customer for a calendar tile similar to the calendar portlet; I was looking at the code of this package and found nothing.

**Comment by datakurre** [comment]
There was in repo history, but was incomplete (browsing did not work) and not updated to Plone 5.

There should be portlet tile available, but disabled by default in the registry. Also it has browsing issue with calendar portlet.

**Comment by hvelarde** [comment]
thnks!

**Comment by thet** [comment]
It should be easy to create a calendar tile based on the code from plone.app.event's calendar portlet.

The browsing issue might have something to do with the calendar portlet ajax-loaading/replacing itself when changing months.

**Comment by hvelarde** [comment]
FYI @rodfersou

**Comment by hvelarde** [comment]
@thet we need to have a calendar tile ready ASAP; we ended cloning the calendar portlet code as a first iteration: https://github.com/collective/collective.cover/pull/632

to be able to reuse plone.app.event code we need to create a mixin with all methods that must be shared among the portlet and a tile.

that would be a future enhancement if you agree.
