### ISSUE TITLE
Insert html in RichText tile?

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.standardtiles#77]
I would like to insert html to RichText/HTML tile. If I set Wysiwyg editor to "None" in "Personale Preferences" I still have it for this tile. I also tried to add "toolbar-code" button to the tiles toolbar but it does not  appear. Is there a way to insert html to RichText tile or do I have to create an extra tile for that?

**Comment by jensens** [comment]
The TinyMCE offers a source code edit feature which works fine here (Plone 5.1-latest + p.a.standardtiles). Please reopen if you think this is still an issue.
